version: "3.9"

networks:
  alex3koval-local:
    external: true

services:
  notification_service:
    container_name: notification_service
    platform: linux/amd64
    networks:
      - alex3koval-local
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10251:${APP_SERVER_PORT}"

  eventer_app:
    container_name: eventer_app
    platform: linux/amd64
    networks:
      - alex3koval-local
    env_file:
      - .env
    build:
      context: .
      dockerfile: EventerApp.Dockerfile
    ports:
      - "10252:${APP_SERVER_PORT}"
    depends_on:
      - notification_service_db

  notification_service_db:
    container_name: notification_service_db
    platform: linux/amd64
    image: postgres:16
    networks:
      - alex3koval-local
    env_file:
      - ".env"
    ports:
      - "5437:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    restart: unless-stopped

  migrator:
    container_name: migrator
    platform: linux/amd64
    image: flyway/flyway:10.20.0-alpine
    command: migrate
    env_file:
      - .env
    environment:
      FLYWAY_URL: $POSTGRES_JDBC_URL
      FLYWAY_USER: $POSTGRES_USER
      FLYWAY_PASSWORD: $POSTGRES_PASSWORD
      FLYWAY_OUT_OF_ORDER: true
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - alex3koval-local

  kafka:
    container_name: kafka
    platform: linux/amd64
    networks:
      - alex3koval-local
    image: 'bitnami/kafka:3.7.0'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL_SAME_HOST://0.0.0.0:29092, CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092, EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=S40B8iVtR0umuTyuM1eLjA
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - ./volume-kafka:/bitnami/kafka

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: kafka_ui
    platform: linux/amd64
    ports:
      - "10249:8080"
    networks:
      - alex3koval-local
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
