app:
  mailer:
    sender_address: ${APP_MAILER_SENDER_ADDRESS}
    max_of_attempts: ${APP_MAILER_MAX_OF_ATTEMPTS}
    otp_template_folder_path: ${APP_MAILER_OTP_TEMPLATE_FOLDER_PATH}
    otp_template_name: ${APP_MAILER_OTP_TEMPLATE_NAME}
  eventer:
    topic-params: [
      {
        topic: "phoneVerification",
        group_id: "verification"
      },
      {
        topic: "emailVerification",
        group_id: "verification"
      }
    ]
  sms:
    otp-template-json-file-path: ${APP_SMS_OTP_TEMPLATE_JSON_FILE_PATH}
  cdc:
    publication-name: ""
    slot-name: ""
    name: ""
    plugin-name: ""
    offset-storage-class: "org.apache.kafka.connect.storage.FileOffsetBackingStore"
    offset-storage-file-name: ""
    offset-flush-interval-millis: 12345
    db-server-name: ""
    db-host: ""
    db-port: 123456
    db-user: ""
    db-password: ""
    db-name: ""
    table-white-list: ""
    column-include-list: ""

server:
  port: ${APP_SERVER_PORT}

spring:
  main:
    web-application-type: reactive
  mail:
    host: smtp.yandex.ru
    port: 465
    username: Koval3nich
    password: gqntfohlgaddeknn
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages.packages: "*"
      enable-auto-commit: false
    admin:
      auto-create: off
      properties:
        client.id: my-admin-client
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVER}

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: false
    suffix: ".html"
  r2dbc:
    url: ${POSTGRES_R2DBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  data:
    r2dbc:
      repositories:
        enabled: true
  #    url: jdbc:postgresql://localhost:5436/auth_service

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: false
        exponential-backoff-multiplier: 2
        enable-random-wait: false
    instances:
      otpRetry:
        base-config: default
        retry-exceptions:
          - java.lang.RuntimeException
          - java.lang.Exception
